---
apiVersion: apps/v1
kind: Deployment                        # Type of K8s resource
metadata: 
  name: go-kube-hello-world             # Name of the K8s service
spec:
  replicas: 3                           # Number of pods to run at any given time
  selector:
    matchLables:
      app: go-kube-hello-world          # This deployment applies to any Pods matching the specified labels
    template:
      metadata:
        labels:                         # The labels that will be applied to all the pods in deployment
          app: go-kube-hello-world
      specs:                            # Spec for the conatiner which will run in the Pod
        containers:
        - name: go-kube-hello-world
          image: anishkargaonkar/go-kube-hello-world:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080       # Should match the port number that the Go application listens on
          livenessProbe:                # To check the health of the Pod
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:                # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
